apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-jp1-blue-green
spec:
  replicas: 6     # i just added it to my file 
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - name: blue-green
          image: mtinside/blue-green:green
          imagePullPolicy: Always
