apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1    # i just added it to my file 
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - name: blue-green
          image: mtinside/blue-green:blue
          imagePullPolicy: Always
