apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jp1-application-argocd 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joephilippe/argocd-jp1.git  
    targetRevision: HEAD
    path:  argocd-jp1-chart/templates/
  destination:
    server: https://kubernetes.default.svc  
    namespace: jp1  # give ur own name # this is new ns that u want argocd to create

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true  